package com.miaoshaproject.dao;

import com.miaoshaproject.dataobject.UserpasswordDO;

public interface UserpasswordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Tue Dec 18 16:36:45 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Tue Dec 18 16:36:45 CST 2018
     */
    int insert(UserpasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Tue Dec 18 16:36:45 CST 2018
     */
    int insertSelective(UserpasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Tue Dec 18 16:36:45 CST 2018
     */
    UserpasswordDO selectByPrimaryKey(Integer id);
    UserpasswordDO selectByUserId(Integer userId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Tue Dec 18 16:36:45 CST 2018
     */
    int updateByPrimaryKeySelective(UserpasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Tue Dec 18 16:36:45 CST 2018
     */
    int updateByPrimaryKey(UserpasswordDO record);
}